### PR TITLE
Consolidate forks

### PR DESCRIPTION
**Pull request by Akababa**
I'd like to submit a PR but it's difficult with so many nested forks

### CODE REVIEW

**Comment by andrewjmetzger** [comment]
Hi @Akababa! Sorry about that, these projects have been awfully fragmented as of late. At this point, I'm tempted to nuke my own copy of MRB (last updated July 2019) and fork this one to start over, merging in these PRs along the way. You could of course do something similar in your own repo, if you wish. Whatever you decide, let me know; I'll do my utmost to help.

**Comment by andrewjmetzger** [comment]
To @LjMario007: If you would like some help, I would gladly take the role of co-maintainer to help sort out these PRs, as well as the project in general. To add me as a Collaborator, go to the repository Settings, then Collaborators, and then type my username `andrewjmetzger`). If you'd prefer instructions with screenshots, GitHub Support also has an article on [Inviting Collaborators to a repository](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository)

While you're in the settings, please also [enable GitHub's free issue tracker](https://help.github.com/en/github/managing-your-work-on-github/disabling-issues) -- although it seems to be disabled at the moment, it's often a better place for discussions such as these.

**Comment by Akababa** [comment]
I'm fine with any solution that lets me submit a PR without the responsibility of maintainership ;)

**Comment by andrewjmetzger** [comment]
Entirely understandable. I'd say we give @LjMario007 a while to respond, but I'm fine with taking over either way.

Just curious: Is there a better way to "update" my fork than deleting the whole thing and forking this repo? I'd like to preserve commit history, if possible.

**Comment by LjMario007** [comment]
See above.
PS @andrewjmetzger with git you can always revert back to a prior commit state; [it's much easier on GitHub Desktop](https://github.com/LjMario007/Microsoft-Rewards-Bot/issues/3), but you can always [do it with the cli](https://gist.github.com/gunjanpatel/18f9e4d1eb609597c50c2118e416e6a6).

**Comment by andrewjmetzger** [comment]
Ah. I'd  like to "fast forward" so-to-speak, to where your fork is at right now so that I can contribute. I suppose I should just change the git remote and pull?

**Comment by LjMario007** [comment]
Yeah, or just delete the local copy and git clone this repo.

**Pull request merged**
