### PR TITLE
Update: 08.11.2020

### PR DESCRIPTION
**Pull request by velotoxicsounds**
## Last-Update

**2020.11.08**
- Fixed bug: get_point_total works again 
- Started to rewrite XPath

**2020.11.04**
- Logging Info customized, new text structure
- New user agent for PC/EDGE
- New login method / cookie query imelemented
- Time Sleep re-adjusted, BOT IS NUN SUPER FAST!
- Random search count, looks significantly more human
- Wait_until_visible activated!
- Sleep Timer for Daily Poll customized, BOT SUPER FAST!!
- Sleep Timer customized for Click Quiz, BOT SUPER FAST!!
- Sleep timer for drag ang drop customized, BOT SUPER FAST!!
- Sleep timer for drag ang drop customized, BOT SUPER FAST!!
- Points are now read correctly at Level 2 Account - Account Level 1 still needs to be implemented
- ensure_pc_mode_logged_in rewritten, BOT SUPER FAST!!
- ensure_mobile_mode_logged_in rewritten, BOT SUPER FAST!!
- Points are now carried in the log

### CODE REVIEW

**Comment by koderian** [comment]
@velotoxicsounds Can you enable issues on your repo, `velotoxicsounds/Microsoft-Rewards-Bot`? I'm going to use your repo from now on instead of this branch

**Comment by koderian** [comment]
Using @velotoxicsounds repo, when I run `python3.8 ms_rewards_login_dict.json --headless --mobile --pc --quiz` (I am using Ubuntu 20.04 headless server) It instantly returns me back to terminal.

I've run pgrep chrome to make sure there isn't any browser instances running, and there wasn't. 

I did install the requisites with `pip3 install -r requirements.txt`

**Comment by velotoxicsounds** [comment]
> @velotoxicsounds Can you enable issues on your repo, `velotoxicsounds/Microsoft-Rewards-Bot`? I'm going to use your repo from now on instead of this branch

FIX

**Comment by velotoxicsounds** [comment]
> Using @velotoxicsounds repo, when I run `python3.8 ms_rewards_login_dict.json --headless --mobile --pc --quiz` (I am using Ubuntu 20.04 headless server) It instantly returns me back to terminal.
> 
> I've run pgrep chrome to make sure there isn't any browser instances running, and there wasn't.
> 
> I did install the requisites with `pip3 install -r requirements.txt`

Try:
python3.8 ms_rewards.py --headless --mobile --pc --quiz

**Comment by velotoxicsounds** [comment]
The project will no longer be supported. Microsoft has found a new anti-bot measure and detected all my accounts. Closed

**Pull request closed without merging**
